
version: '3.8'
services:
  webserver:
    image: httpd:2.4
    ports:
      - "8080:80"
    volumes :
      - ./html:/usr/local/apache2/htdocs:ro
    restart: unless-stopped
  db:
      image: mysql:8
      container_name: mysql-server
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: secure_password
        MYSQL_DATABASE: mydb
        MYSQL_USER: myuser
        MYSQL_PASSWORD: password
      ports:
        - "3306:3306"
      volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: